### ISSUE TITLE
学校签到失败，怎么解

### ISSUE THREAD

**Issue by Charonics** [Ecalose/ptsign#4]
ptschool签到失败，配置上需要注意什么吗，是需要配置代理？user-agent？
另，使用telegram通知代理如何配

学校 账号数为 1 个，开始签到：
ptschool : 签到失败

**Comment by Ecalose** [comment]
可以尝试添加与抓包cookie对应的ua，并更换签到的时间段
tg代理暂不支持

**Comment by Charonics** [comment]
[[ptschool]]
name = "ptschool"
url = "https://pt.btschool.club/index.php?action=addbonus"
cookie=""

ua直接添加在配置文件这里吗，后面跟一个？字段ueser-agent？能识别吗

**Comment by Ecalose** [comment]
这样
[[ptschool]]
name = "ptschool"
url = "host/index.php?action=addbonus"
cookie=""
ua=""
[配置文件](https://github.com/Ecalose/MyCheckBox/blob/18c443418813c6ba866389d42ac9eca6f46183c4/config.toml#L41-L45)已更新
